import os
import numpy as np
import pandas as pd
import shutil

from settings import DIR_DATA_EXPT, DIR_FITS

"""
Open the 'fit summary' csv file generated by Stan inference via fit_experiment_data.py
  1) Make a copy of the file with the same name but with '-habscores' appended to the filename.
  2) Load as a pandas dataframe. Add additional columns (various metrics of habituation).
  3) Save the new dataframe to the new file.

Note: 
- These functions assume that the posterior draws are for the parameters [alpha, beta, p0].
- These functions were derived by assuming the quadratic link function f(x) = 1 / (1 + x^2).

Overview of new 'habscore' columns:
- T1_x_ss: Steady state internal state for T=1.
- T1_hab_mag_rel: Relative magnitude of habituation for T=1.
- T1_hab_mag_abd: Absolute magnitude of habituation for T=1.
- T1_hab_time_half_rel: Time to 50% habituation for T=1.
- T1_hab_time_95_rel: Time to 95% habituation for T=1.
- T1_hab_time_half_abs: Time to 50% absolute habituation for T=1. (Can be NaN if x_ss <= 1)

For each, we report several summary stats (mean, median, std, 95% CI) and analogous columns for T=5s (SRA assay).
"""

# Define functions for derived quantities (for T=1 assay).
# - here we assume each posterior draw gives parameters [alpha, beta, p0].
def compute_x_ss(alpha, beta, T=1):
    # Steady state internal state at T=1.
    return beta * np.exp(-alpha * T) / (1 - np.exp(-alpha * T))

def compute_p_ss(alpha, beta, p0, T=1):
    # Steady state probability at T=1.
    xss = compute_x_ss(alpha, beta, T=T)
    return p0 / (1 + xss ** 2)

def compute_hab_magnitude_rel(alpha, beta, T=1):
    # Using a quadratic link: p(x) = p0/(1+x^2). So the asymptotic (steady-state) probability is p_inf = p0/(1+(x*)^2).
    # - The relative magnitude (drop) is defined as 1 - p_inf/p0.
    xss = compute_x_ss(alpha, beta, T=T)
    p_inf = 1 / (1 + xss ** 2)  # note: here p0 cancels if p0 is assumed constant (or equals 1)
    return 1 - p_inf

def compute_hab_magnitude_abs(alpha, beta, p0, T=1):
    # - The absolute magnitude (drop) is defined as p0 - p_inf
    hab_magnitude_rel = compute_hab_magnitude_rel(alpha, beta, T=T)
    return p0 * hab_magnitude_rel

def compute_hab_time_half_rel(alpha, beta, T=1):
    # Analytic half-life for quadratic link.
    #   - define R[k] = (p[k] - p_inf) / (p0 - p_inf) as the normalized response
    #   - solve for R[k_z] = z for k, given z=0.05 or z=0.5
    #   - derived earlier: k_{1/2} = -1/(alpha*T)*ln(1 - 1/sqrt((x*)^2+2))
    xss = compute_x_ss(alpha, beta, T=T)
    return -1 / (alpha * T) * np.log(1 - 1 / np.sqrt(xss ** 2 + 2))

def compute_hab_time_95_rel(alpha, beta, T=1):
    # Analytic time-to-95% saturation (i.e. normalized response = 0.05).
    #   - see docstring for compute_hab_time_half_rel(...)
    #   - derived earlier: k_{0.05} = -1/(alpha*T)*ln(1 - sqrt(0.95/(1+0.05*(x*)^2))).
    xss = compute_x_ss(alpha, beta, T=T)
    return -1 / (alpha * T) * np.log(1 - np.sqrt(0.95 / (1 + 0.05 * xss ** 2)))

def compute_hab_time_half_abs(alpha, beta, T=1):
    # - define alternative time-to-habituate as time when x(t) = 1  <->  p_jump(t) = p0 / 2, given sigma(x) = 1 / (1 + x^2)
    #   - if x_ss = beta / (1 - np.exp(-alpha)) < 1, then x(t) never hits 1, so set to NaN
    xss = compute_x_ss(alpha, beta, T=T)
    return 1 / (alpha * T) * np.log(xss / (xss - 1))

def helper_summarize_univariate_samples(x):
    """
    x in an array of size (n_draws,) which we wish to summarize
    """
    def median_helper(x, nan_replace=1e8):
        # replace NaNs with a large number to avoid NaN forcing
        #   e.g. [1, 1, 1, 2, np.nan, 1]                     -> median should be 1
        #   e.g. [np.nan, np.nan, np.nan, np.nan, np.nan, 1] -> median should be np.nan
        arr = np.nan_to_num(x, nan=nan_replace)
        arr = np.median(arr)
        return np.where(arr < 1e3, arr, np.nan)

    return {
        'mean':     np.mean(x),        # is any samples in x are NaN, this should be NaN
        'median':   median_helper(x),  # this however may not be NaN
        'std':      np.std(x),
        'CI_lower': np.percentile(x, 2.5),
        'CI_upper': np.percentile(x, 97.5)
    }


def load_draws_for_model(model_type='3d'):
    """
    Load NPZ draws for specified model type.

    Args:
        model_type: '3d', '2d', or '1d'

    Returns:
        dict: {genotype: {day: npz_object}}
    """
    suffix = f"_{model_type}" if model_type in ['3d', '2d', '1d'] else ""

    draws_GD_day7 = np.load(DIR_FITS + os.sep + f"GD_day7{suffix}_draws.npz", allow_pickle=True)
    draws_GD_day14 = np.load(DIR_FITS + os.sep + f"GD_day14{suffix}_draws.npz", allow_pickle=True)
    draws_GD_day21 = np.load(DIR_FITS + os.sep + f"GD_day21{suffix}_draws.npz", allow_pickle=True)

    draws_KK_day7 = np.load(DIR_FITS + os.sep + f"KK_day7{suffix}_draws.npz", allow_pickle=True)
    draws_KK_day14 = np.load(DIR_FITS + os.sep + f"KK_day14{suffix}_draws.npz", allow_pickle=True)
    draws_KK_day21 = np.load(DIR_FITS + os.sep + f"KK_day21{suffix}_draws.npz", allow_pickle=True)

    return {
        'KK': {7: draws_KK_day7, 14: draws_KK_day14, 21: draws_KK_day21},
        'GD': {7: draws_GD_day7, 14: draws_GD_day14, 21: draws_GD_day21}
    }


if __name__ == '__main__':

    # Process each model type in turn.
    model_type = '3d'  # change to '2d' or '1d' as needed

    if model_type not in ['3d', '2d', '1d']:
        raise ValueError(f"model_type must be '3d', '2d', or '1d', got '{model_type}'")

    print(f"\n{'='*70}")
    print(f"Processing {model_type.upper()} model fits")
    print(f"{'='*70}")

    # File paths (adjust as needed)
    summary_csv_path = os.path.join(DIR_FITS, f'fly-stability-days-detailed-{model_type}.csv')

    # Load posterior draws for multiple days/genotypes
    # Given e.g. KK_day14, each key is like "fly_id_1", "fly_id_2", etc. Each value is an array of shape (n_draws, n_params)
    draws_over_age = load_draws_for_model(model_type)

    # Create a new file name for the updated summary CSV.
    new_summary_csv_path = summary_csv_path.replace('.csv', '-habscores.csv')
    shutil.copy(summary_csv_path, new_summary_csv_path)

    # Load the summary CSV
    df_summary_csv = pd.read_csv(new_summary_csv_path)

    # Now, loop over each fly in the draws file and compute the distribution for each derived metric.
    # We'll create a dictionary where the key is the fly_id and the value is a dictionary of summary statistics.
    fly_stats_list = []

    # For each fly (each row of the summary csv):
    #   1) load the appropriate draws values for alpha, beta and p0
    #   2) compute the derived quantities for each draw
    #   3) summarize the distribution of each derived quantity (at the end we will append the df rows to a new csv)

    # Loop over each row in the DataFrame.
    for idx, row in df_summary_csv.iterrows():
        fly_id = row['fly_id']
        age = row['day']
        gbr = row['genotype']

        # 1) now access the corresponding draws data for this experiment
        draws = draws_over_age[gbr][age]['fly_id_%d' % fly_id]

        print('Working on fly_id %d, age %d, genotype %s, model %s' % (fly_id, age, gbr, model_type))

        # 2) Extract parameter draws based on model type
        if model_type == '3d':
            # 3D: draws shape is (n_draws, 3) -> [alpha, beta, p0]
            alpha_draws = draws[:, 0]
            beta_draws  = draws[:, 1]
            p0_draws    = draws[:, 2]
        elif model_type == '2d':
            # 2D: draws shape is (n_draws, 2) -> [beta, p0]
            # alpha is fixed at alpha_global (constant for this genotype+day pair)
            alpha_global = row['alpha']  # condition-specific alpha_global
            alpha_draws = np.full(len(draws), alpha_global)
            beta_draws  = draws[:, 0]
            p0_draws    = draws[:, 1]
        elif model_type == '1d':
            # 1D: draws shape is (n_draws, 1) -> p0 only
            # No alpha or beta - will set derived metrics to NaN
            alpha_draws = None
            beta_draws  = None
            p0_draws    = draws[:, 0]  # extract from 2D array

        # 3) Summarize the distribution for each derived quantity.
        fly_stats = {'fly_id': fly_id, 'day': age, 'genotype': gbr}

        # Compute derived metrics (skip for 1D model - no dynamics)
        if model_type == '1d':
            # For 1D model, set all derived metrics to NaN
            for T_period in [1, 5]:
                for label in ['T%d_x_ss' % T_period,
                              'T%d_hab_mag_rel' % T_period,
                              'T%d_hab_mag_abs' % T_period,
                              'T%d_hab_time_half_rel' % T_period,
                              'T%d_hab_time_95_rel' % T_period,
                              'T%d_hab_time_half_abs' % T_period]:
                    fly_stats[label + '_mean'] = np.nan
                    fly_stats[label + '_median'] = np.nan
                    fly_stats[label + '_std'] = np.nan
                    fly_stats[label + '_CI_lower'] = np.nan
                    fly_stats[label + '_CI_upper'] = np.nan
        else:
            # For 2D and 3D models, compute all derived metrics
            for T_period in [1, 5]:
                for label, draws_array in [
                    ('T%d_x_ss' % T_period,
                     compute_x_ss(alpha_draws, beta_draws, T=T_period)),
                    ('T%d_hab_mag_rel' % T_period,
                     compute_hab_magnitude_rel(alpha_draws, beta_draws, T=T_period)),
                    ('T%d_hab_mag_abs' % T_period,
                     compute_hab_magnitude_abs(alpha_draws, beta_draws, p0_draws, T=T_period)),
                    ('T%d_hab_time_half_rel' % T_period,
                     compute_hab_time_half_rel(alpha_draws, beta_draws, T=T_period)),
                    ('T%d_hab_time_95_rel' % T_period,
                     compute_hab_time_95_rel(alpha_draws, beta_draws, T=T_period)),
                    ('T%d_hab_time_half_abs' % T_period,
                     compute_hab_time_half_abs(alpha_draws, beta_draws, T=T_period))
                ]:
                    stats = helper_summarize_univariate_samples(draws_array)
                    fly_stats[label + '_mean'] = stats['mean']
                    fly_stats[label + '_median'] = stats['median']
                    fly_stats[label + '_std'] = stats['std']
                    fly_stats[label + '_CI_lower'] = stats['CI_lower']
                    fly_stats[label + '_CI_upper'] = stats['CI_upper']

        # We append these summaries to the DataFrame row (or store in a dictionary for later merging).
        fly_stats_list.append(fly_stats)

    # Convert the list of fly summary dictionaries to a DataFrame.
    df_fly_stats = pd.DataFrame(fly_stats_list)

    # Merge the new summaries with the original summary CSV on fly_id, day, and genotype.
    # (Make sure these keys are common to both DataFrames.)
    df_updated = pd.merge(df_summary_csv, df_fly_stats, on=['fly_id', 'day', 'genotype'], how='left')

    # Save the new DataFrame with appended columns to a new CSV file.
    df_updated.to_csv(new_summary_csv_path, index=False, na_rep='NA')
    print(f"\n{'='*70}")
    print(f"{model_type.upper()} model: Updated summary CSV saved to:")
    print(f"  {new_summary_csv_path}")
    print(f"{'='*70}")
